### ISSUE TITLE
Allow running for non-login interactive shells to support the typical xterm use-case

### ISSUE THREAD

**Issue by ajsalminen** [oldratlee/hacker-quotes#2]
Right now the quote typically won't print when opening a new xterm inside X11. Could the check for interactive login shells be changed to just checking for an interactive shell? Or maybe add a variable that lets it open for all interactive shells if current behavior should still be possible?

**Comment by oldratlee** [comment]
@ajsalminen Your advise makes more sense! 

Fixed.

PS: Sorry for my slow rely! 😬
