### ISSUE TITLE
Please Add Option to Readme.md for SSH keyholders

### ISSUE THREAD

**Issue by bryan-snyder** [oldratlee/hacker-quotes#4]
using your clone option ... anyone with a SSH key pair with github will get denied and they need to clone using the HTTPS address.

maybe you could update the readme.md to express this difference.

thanks!
B

**Comment by oldratlee** [comment]
You're right. 

Would you mind send a PR? ❤️😄

**Comment by technofantods** [comment]
lol, sure.

**Comment by oldratlee** [comment]
added `git clone https://github.com/oldratlee/hacker-quotes.git ~/.oh-my-zsh/custom/plugins/hacker-quotes` in README.
